version: '3'

services:
  backend:
    image: 
      "tanatry/back-test"
    ports: 
      - "8080:8080"
  forntend:
    image: 
      "tanatry/fornt-test"
    ports: 
      - "4200:4200"
    links:
      - "backend"
    depends_on:
      - "backend"